---
title: The Muscle-BIDS Project
description: Standardizing Muscle MR image processing
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji
- github-pages
- jekyll-remote-theme # add this line to the plugins list if you already have one

repository: muscle-bids/muscle-bids

sections:
- label: Home
  url: /
- label: Specification
  url: /specs
- label: Python package
  url: /package
